name: CI Android Release Build (APK) # Nom mis Ã  jour

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'
          channel: 'stable'

      - name: Get Flutter Dependencies
        run: flutter pub get
      
      # Configuration de la signature (Identique)
      - name: Setup Signing Credentials (Keystore)
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release.jks
          echo "storeFile=release.jks" > android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties

      - name: Build Android APK
        # ðŸš¨ COMMANDE CLÃ‰ MODIFIÃ‰E
        run: flutter build apk --release

      - name: Upload Artifact (TÃ©lÃ©chargement)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk # Nom du fichier Ã  tÃ©lÃ©charger
          # ðŸš¨ CHEMIN CLÃ‰ MODIFIÃ‰
          path: build/app/outputs/apk/release/app-release.apk